# Generated by Django 5.2.14 on 2026-05-11 05:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم الموظف"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الكامل"),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رقم الهوية"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "ذكر"), ("F", "أنثى")],
                        max_length=1,
                        verbose_name="الجنس",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                ("hire_date", models.DateField(verbose_name="تاريخ التوظيف")),
                (
                    "department",
                    models.CharField(blank=True, max_length=200, verbose_name="القسم"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="المسمى الوظيفي"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الجوال"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="البريد الإلكتروني"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
            ],
            options={
                "verbose_name": "موظف",
                "verbose_name_plural": "الموظفون",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم السياسة")),
                (
                    "inpatient_coverage_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=90.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة تغطية المريض الداخلي (%)",
                    ),
                ),
                (
                    "outpatient_coverage_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=70.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="نسبة تغطية الطوارئ والعيادات الخارجية (%)",
                    ),
                ),
                (
                    "employee_annual_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=10000.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="السقف السنوي للموظف (ريال)",
                    ),
                ),
                (
                    "family_member_annual_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=7000.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="السقف السنوي لكل فرد من العائلة (ريال)",
                    ),
                ),
                (
                    "max_per_claim",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000.0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="الحد الأقصى للمطالبة الواحدة (ريال)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "إعدادات التأمين",
                "verbose_name_plural": "إعدادات التأمين",
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="الاسم الكامل"),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهوية"
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("spouse", "زوج/زوجة"),
                            ("son", "ابن"),
                            ("daughter", "ابنة"),
                            ("father", "والد"),
                            ("mother", "والدة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="صلة القرابة",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="تاريخ الميلاد")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_members",
                        to="insurance.employee",
                        verbose_name="الموظف",
                    ),
                ),
            ],
            options={
                "verbose_name": "فرد العائلة",
                "verbose_name_plural": "أفراد العائلة",
            },
        ),
        migrations.CreateModel(
            name="InsuranceClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claim_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رقم المطالبة"
                    ),
                ),
                (
                    "beneficiary_type",
                    models.CharField(
                        choices=[("employee", "الموظف"), ("family", "فرد من العائلة")],
                        max_length=10,
                        verbose_name="المستفيد",
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("inpatient", "مريض داخلي (رقود)"),
                            ("outpatient", "عيادات خارجية"),
                            ("emergency", "طوارئ"),
                        ],
                        max_length=20,
                        verbose_name="نوع المطالبة",
                    ),
                ),
                ("claim_date", models.DateField(verbose_name="تاريخ الخدمة الطبية")),
                (
                    "submission_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ التقديم"),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        max_length=300, verbose_name="اسم المستشفى / العيادة"
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="التشخيص / السبب الطبي")),
                (
                    "invoice_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="قيمة الفاتورة (ريال)",
                    ),
                ),
                (
                    "coverage_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=5,
                        verbose_name="نسبة التغطية (%)",
                    ),
                ),
                (
                    "insurance_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="مبلغ التأمين (ريال)",
                    ),
                ),
                (
                    "employee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=12,
                        verbose_name="مبلغ تحمل الموظف (ريال)",
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="المبلغ المعتمد (ريال)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد المراجعة"),
                            ("approved", "مقبولة"),
                            ("partially_approved", "مقبولة جزئياً"),
                            ("rejected", "مرفوضة"),
                            ("paid", "مدفوعة"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="سبب الرفض"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="insurance.employee",
                        verbose_name="الموظف",
                    ),
                ),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="insurance.familymember",
                        verbose_name="فرد العائلة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مطالبة تأمين",
                "verbose_name_plural": "مطالبات التأمين",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("invoice", "فاتورة طبية"),
                            ("doctor_request", "طلب طبيب"),
                            ("prescription", "وصفة طبية"),
                            ("lab_result", "نتيجة مختبر"),
                            ("xray", "أشعة"),
                            ("discharge_summary", "ملخص خروج"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع المستند",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="claims/%Y/%m/", verbose_name="الملف"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="وصف"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="insurance.insuranceclaim",
                        verbose_name="المطالبة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستند",
                "verbose_name_plural": "المستندات",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="insurance_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="insurance.insurancesettings",
                verbose_name="سياسة التأمين",
            ),
        ),
    ]
