--------------------------------------------------------------------------------
-- SPMS - نظام إدارة التخطيط الاستراتيجي
-- جامعة العلوم والتكنولوجيا - عدن | إدارة تقنية المعلومات
--
-- Prompt P1 - قاعدة البيانات: مخطط قاعدة البيانات (DDL)
-- استناداً إلى القسم 3 (نموذج البيانات) والقرارات المعمارية في القسم 0
-- من SPMS_Technical_Spec_for_Claude_Code.
--
-- نطاق هذا السكربت (P1 فقط):
--   * كل الجداول بأعمدتها ومفاتيحها الأساسية والأجنبية.
--   * أعمدة التدقيق القياسية على كل جدول جوهري: created_by/at, updated_by/at, is_active.
--   * Soft-delete فقط (AD-06) - لا حذف فيزيائي للكيانات الجوهرية.
--   * ترميز AL32UTF8 - يُضبط عند إنشاء قاعدة البيانات / الـ Pluggable Database
--     (NLS_CHARACTERSET)، وليس داخل هذا السكربت.
--   * فهارس على المفاتيح الأجنبية وأعمدة الاستعلام المتكرر (org_unit_id, academic_year, target_year).
--   * قيود CHECK على الحقول المعدودة (status, unit_type, period_type, ...).
--
-- لا يُنفَّذ أي منطق أعمال هنا (لا حزم PL/SQL، لا Triggers إجرائية) - ذلك في
-- Prompt P2 (PKG_INHERITANCE), Prompt P3 (PKG_CALC + AUDIT_LOG triggers)
-- و Prompt P4 (PKG_SECURITY).
--
-- السكربت قابل للتشغيل مرة واحدة على مخطط (schema) فارغ، بترتيب يحترم
-- تبعيات المفاتيح الأجنبية.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. الهيكل التنظيمي والمستخدمون (القسم 3.1)
--------------------------------------------------------------------------------

-- ORG_UNITS: الوحدات التنظيمية للجامعة على شكل شجرة (رئاسة/عمادة/كلية/قسم/فرع...)
CREATE TABLE org_units (
    org_unit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       NUMBER,
    unit_type       VARCHAR2(30)  NOT NULL,
    name_ar         VARCHAR2(200) NOT NULL,
    name_en         VARCHAR2(200),
    level_no        NUMBER(3),
    created_by      NUMBER,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP,
    is_active       NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at      TIMESTAMP,
    CONSTRAINT fk_org_units_parent FOREIGN KEY (parent_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_org_units_type CHECK (unit_type IN
        ('PRESIDENCY', 'VP_OFFICE', 'COLLEGE', 'DEANSHIP', 'DEPARTMENT', 'BRANCH', 'ADMIN')),
    CONSTRAINT ck_org_units_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE org_units IS 'الوحدات التنظيمية للجامعة (شجرة هرمية) - الجذر (رئاسة الجامعة) بدون parent_id';
COMMENT ON COLUMN org_units.parent_id IS 'FK ذاتي، NULL للجذر (رئاسة الجامعة)';
COMMENT ON COLUMN org_units.level_no IS 'عمق الوحدة في الشجرة، لأغراض الاستعلام السريع';

CREATE INDEX ix_org_units_parent ON org_units (parent_id);

-- USERS: مستخدمو النظام، كل مستخدم مرتبط بجهة تنظيمية واحدة
CREATE TABLE users (
    user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(100) NOT NULL,
    full_name       VARCHAR2(200) NOT NULL,
    email           VARCHAR2(200),
    job_title       VARCHAR2(200),
    org_unit_id     NUMBER        NOT NULL,
    status          VARCHAR2(20)  DEFAULT 'ACTIVE' NOT NULL,
    created_by      NUMBER,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP,
    is_active       NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at      TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT fk_users_org_unit FOREIGN KEY (org_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_users_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE users IS 'مستخدمو النظام';
COMMENT ON COLUMN users.org_unit_id IS 'جهة المستخدم التنظيمية';

CREATE INDEX ix_users_org_unit ON users (org_unit_id);

--------------------------------------------------------------------------------
-- 1.1 نموذج RBAC مرن (القسم 6.1): USERS -> USER_ROLES -> ROLES -> ROLE_PERMISSIONS -> PERMISSIONS
--------------------------------------------------------------------------------

-- ROLES: الأدوار الأساسية (SYS_ADMIN, UNIT_MANAGER, DATA_ENTRY, REVIEWER, VIEWER)
CREATE TABLE roles (
    role_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code       VARCHAR2(30)  NOT NULL,
    name_ar         VARCHAR2(200) NOT NULL,
    name_en         VARCHAR2(200),
    created_by      NUMBER,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP,
    is_active       NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at      TIMESTAMP,
    CONSTRAINT uq_roles_code UNIQUE (role_code),
    CONSTRAINT ck_roles_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE roles IS 'الأدوار الأساسية في النظام';

-- PERMISSIONS: الصلاحيات الذرية (مثل VIEW_REPORT, EDIT_DATA, APPROVE_PLAN)
CREATE TABLE permissions (
    permission_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR2(50)  NOT NULL,
    name_ar         VARCHAR2(200) NOT NULL,
    name_en         VARCHAR2(200),
    created_by      NUMBER,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP,
    is_active       NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at      TIMESTAMP,
    CONSTRAINT uq_permissions_code UNIQUE (permission_code),
    CONSTRAINT ck_permissions_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE permissions IS 'الصلاحيات الذرية لتخصيص مرن يتجاوز الأدوار الثابتة';

-- USER_ROLES: ربط المستخدمين بالأدوار (m:n)
CREATE TABLE user_roles (
    user_id         NUMBER NOT NULL,
    role_id         NUMBER NOT NULL,
    created_by      NUMBER,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (role_id)
);
COMMENT ON TABLE user_roles IS 'ربط المستخدمين بالأدوار';

CREATE INDEX ix_user_roles_role ON user_roles (role_id);

-- ROLE_PERMISSIONS: ربط الأدوار بالصلاحيات (m:n)
CREATE TABLE role_permissions (
    role_id         NUMBER NOT NULL,
    permission_id   NUMBER NOT NULL,
    created_by      NUMBER,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_perm_role FOREIGN KEY (role_id) REFERENCES roles (role_id),
    CONSTRAINT fk_role_perm_perm FOREIGN KEY (permission_id) REFERENCES permissions (permission_id)
);
COMMENT ON TABLE role_permissions IS 'ربط الأدوار بالصلاحيات الذرية';

CREATE INDEX ix_role_permissions_perm ON role_permissions (permission_id);

--------------------------------------------------------------------------------
-- 2. الخطة الاستراتيجية - مع التأريخ الفعّال (AD-01) (القسم 3.2)
--------------------------------------------------------------------------------

-- STRATEGIC_PLANS: الخطة الاستراتيجية الخمسية (إصدارات + تأريخ فعّال)
CREATE TABLE strategic_plans (
    plan_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_ar        VARCHAR2(300) NOT NULL,
    start_year      NUMBER(4)     NOT NULL,
    end_year        NUMBER(4)     NOT NULL,
    status          VARCHAR2(20)  DEFAULT 'DRAFT' NOT NULL,
    version_no      NUMBER(6)     DEFAULT 1 NOT NULL,
    effective_from  DATE,
    created_by      NUMBER,
    created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP,
    is_active       NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at      TIMESTAMP,
    CONSTRAINT ck_strategic_plans_status CHECK (status IN ('DRAFT', 'APPROVED', 'ARCHIVED')),
    CONSTRAINT ck_strategic_plans_years CHECK (end_year >= start_year),
    CONSTRAINT ck_strategic_plans_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE strategic_plans IS 'الخطة الاستراتيجية الخمسية للجامعة، مثال: الخطة الاستراتيجية الثالثة 2026-2030';
COMMENT ON COLUMN strategic_plans.version_no IS 'رقم الإصدار، يبدأ من 1 (AD-01)';
COMMENT ON COLUMN strategic_plans.effective_from IS 'التاريخ الفعّال لهذا الإصدار (AD-01) - التقارير التاريخية لا تتأثر بتعديل لاحق';

-- DIMENSIONS: أبعاد بطاقة الأداء المتوازن (التعلّم والنمو، العمليات الداخلية، المستفيدون، البُعد المالي)
CREATE TABLE dimensions (
    dimension_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id             NUMBER        NOT NULL,
    name_ar             VARCHAR2(300) NOT NULL,
    name_en             VARCHAR2(300),
    weight_pct          NUMBER(5,2),
    is_weight_explicit  NUMBER(1)     DEFAULT 0 NOT NULL,
    display_order       NUMBER(4),
    created_by          NUMBER,
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          NUMBER,
    updated_at          TIMESTAMP,
    is_active           NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at           TIMESTAMP,
    CONSTRAINT fk_dimensions_plan FOREIGN KEY (plan_id) REFERENCES strategic_plans (plan_id),
    CONSTRAINT ck_dimensions_weight CHECK (weight_pct IS NULL OR weight_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_dimensions_weight_flag CHECK (is_weight_explicit IN (0, 1)),
    CONSTRAINT ck_dimensions_weight_pair CHECK (is_weight_explicit = 0 OR weight_pct IS NOT NULL),
    CONSTRAINT ck_dimensions_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE dimensions IS 'أبعاد بطاقة الأداء المتوازن ضمن خطة استراتيجية معينة';
COMMENT ON COLUMN dimensions.weight_pct IS 'الوزن النسبي، حقل اختياري (AD-02)';
COMMENT ON COLUMN dimensions.is_weight_explicit IS '0 = وزن ضمني (توزيع متساوٍ - fallback)، 1 = وزن صريح أدخله المستخدم';

CREATE INDEX ix_dimensions_plan ON dimensions (plan_id);

-- STRATEGIC_OBJECTIVES: الأهداف الاستراتيجية (نفس نمط الوزن الاختياري لـ DIMENSIONS)
CREATE TABLE strategic_objectives (
    strategic_objective_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_id            NUMBER        NOT NULL,
    name_ar                 VARCHAR2(300) NOT NULL,
    name_en                 VARCHAR2(300),
    weight_pct               NUMBER(5,2),
    is_weight_explicit       NUMBER(1)     DEFAULT 0 NOT NULL,
    display_order            NUMBER(4),
    created_by               NUMBER,
    created_at                TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by                NUMBER,
    updated_at                TIMESTAMP,
    is_active                 NUMBER(1)    DEFAULT 1 NOT NULL,
    deleted_at                 TIMESTAMP,
    CONSTRAINT fk_strat_obj_dimension FOREIGN KEY (dimension_id) REFERENCES dimensions (dimension_id),
    CONSTRAINT ck_strat_obj_weight CHECK (weight_pct IS NULL OR weight_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_strat_obj_weight_flag CHECK (is_weight_explicit IN (0, 1)),
    CONSTRAINT ck_strat_obj_weight_pair CHECK (is_weight_explicit = 0 OR weight_pct IS NOT NULL),
    CONSTRAINT ck_strat_obj_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE strategic_objectives IS 'الأهداف الاستراتيجية ضمن بُعد معين';

CREATE INDEX ix_strat_obj_dimension ON strategic_objectives (dimension_id);

-- SUB_OBJECTIVES: الأهداف الفرعية
CREATE TABLE sub_objectives (
    sub_objective_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategic_objective_id   NUMBER        NOT NULL,
    name_ar                  VARCHAR2(300) NOT NULL,
    name_en                  VARCHAR2(300),
    display_order            NUMBER(4),
    created_by                NUMBER,
    created_at                 TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by                 NUMBER,
    updated_at                 TIMESTAMP,
    is_active                  NUMBER(1)    DEFAULT 1 NOT NULL,
    deleted_at                  TIMESTAMP,
    CONSTRAINT fk_sub_obj_strat_obj FOREIGN KEY (strategic_objective_id)
        REFERENCES strategic_objectives (strategic_objective_id),
    CONSTRAINT ck_sub_obj_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE sub_objectives IS 'الأهداف الفرعية ضمن هدف استراتيجي معين';

CREATE INDEX ix_sub_obj_strat_obj ON sub_objectives (strategic_objective_id);

-- KPIS: مؤشرات الأداء الرئيسية
CREATE TABLE kpis (
    kpi_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_objective_id    NUMBER        NOT NULL,
    code                VARCHAR2(30)  NOT NULL,
    name_ar             VARCHAR2(400) NOT NULL,
    unit_measurement    VARCHAR2(50),
    baseline_value      NUMBER(18,4),
    target_cumulative   NUMBER(18,4),
    weight_pct          NUMBER(5,2),
    is_weight_explicit  NUMBER(1)     DEFAULT 0 NOT NULL,
    display_order       NUMBER(4),
    created_by          NUMBER,
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          NUMBER,
    updated_at          TIMESTAMP,
    is_active           NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at           TIMESTAMP,
    CONSTRAINT uq_kpis_code UNIQUE (code),
    CONSTRAINT fk_kpis_sub_obj FOREIGN KEY (sub_objective_id) REFERENCES sub_objectives (sub_objective_id),
    CONSTRAINT ck_kpis_weight CHECK (weight_pct IS NULL OR weight_pct BETWEEN 0 AND 100),
    CONSTRAINT ck_kpis_weight_flag CHECK (is_weight_explicit IN (0, 1)),
    CONSTRAINT ck_kpis_weight_pair CHECK (is_weight_explicit = 0 OR weight_pct IS NOT NULL),
    CONSTRAINT ck_kpis_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE kpis IS 'مؤشرات الأداء الرئيسية ضمن هدف فرعي معين';
COMMENT ON COLUMN kpis.code IS 'كود داخلي (مثال: KPI-26-0001) - REQ-012: يُعرض دائماً الاسم لا الكود في الواجهة';
COMMENT ON COLUMN kpis.target_cumulative IS 'المستهدف التراكمي لكل مدة الخطة (خمس سنوات)';

CREATE INDEX ix_kpis_sub_obj ON kpis (sub_objective_id);

-- KPI_YEARLY_TARGETS: التوزيع اليدوي للمستهدفات السنوية (REQ-030) - لا توزيع آلي متساوٍ
CREATE TABLE kpi_yearly_targets (
    target_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id          NUMBER    NOT NULL,
    target_year     NUMBER(4) NOT NULL,
    value_target    NUMBER(18,4) NOT NULL,
    created_by      NUMBER,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by      NUMBER,
    updated_at      TIMESTAMP,
    is_active       NUMBER(1) DEFAULT 1 NOT NULL,
    deleted_at      TIMESTAMP,
    CONSTRAINT uq_kpi_yearly_targets UNIQUE (kpi_id, target_year),
    CONSTRAINT fk_kpi_yearly_targets_kpi FOREIGN KEY (kpi_id) REFERENCES kpis (kpi_id),
    CONSTRAINT ck_kpi_yearly_targets_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE kpi_yearly_targets IS 'REQ-030: مستهدف سنوي لكل مؤشر، يُدخل يدوياً - لا يوجد توزيع آلي متساوٍ مفروض';

CREATE INDEX ix_kpi_yearly_targets_year ON kpi_yearly_targets (target_year);

-- PROJECTS: المشاريع (مرتبطة بمؤشر أداء)
CREATE TABLE projects (
    project_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kpi_id              NUMBER        NOT NULL,
    name_ar             VARCHAR2(300) NOT NULL,
    description         VARCHAR2(4000),
    responsible_unit_id NUMBER        NOT NULL,
    start_date          DATE,
    end_date            DATE,
    approval_status     VARCHAR2(20)  DEFAULT 'DRAFT' NOT NULL,
    created_by          NUMBER,
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          NUMBER,
    updated_at          TIMESTAMP,
    is_active           NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at           TIMESTAMP,
    CONSTRAINT fk_projects_kpi FOREIGN KEY (kpi_id) REFERENCES kpis (kpi_id),
    CONSTRAINT fk_projects_unit FOREIGN KEY (responsible_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_projects_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_projects_approval CHECK (approval_status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_projects_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE projects IS 'المشاريع، كل مشروع مرتبط بمؤشر أداء رئيسي واحد';

CREATE INDEX ix_projects_kpi ON projects (kpi_id);
CREATE INDEX ix_projects_unit ON projects (responsible_unit_id);

-- ACTIVITIES: الأنشطة - نقطة إدخال واحدة (REQ-005)، لا تكرار عبر شاشات أخرى
CREATE TABLE activities (
    activity_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id            NUMBER        NOT NULL,
    name_ar               VARCHAR2(300) NOT NULL,
    responsible_unit_id   NUMBER        NOT NULL,
    target_count          NUMBER(10),
    start_date            DATE,
    end_date              DATE,
    created_by            NUMBER,
    created_at            TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by            NUMBER,
    updated_at            TIMESTAMP,
    is_active             NUMBER(1)     DEFAULT 1 NOT NULL,
    deleted_at              TIMESTAMP,
    CONSTRAINT fk_activities_project FOREIGN KEY (project_id) REFERENCES projects (project_id),
    CONSTRAINT fk_activities_unit FOREIGN KEY (responsible_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_activities_dates CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_activities_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE activities IS 'قاعدة: النشاط يُدخل من نافذة واحدة فقط ويُستدعى في بقية الشاشات - لا جدول تكرار (REQ-005)';

CREATE INDEX ix_activities_project ON activities (project_id);
CREATE INDEX ix_activities_unit ON activities (responsible_unit_id);

-- SUPPORTING_UNITS: جدول ربط m:n للجهات المشاركة/المساندة في مشروع أو نشاط
CREATE TABLE supporting_units (
    supporting_unit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type         VARCHAR2(20) NOT NULL,
    entity_id           NUMBER       NOT NULL,
    org_unit_id         NUMBER       NOT NULL,
    created_by          NUMBER,
    created_at          TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    is_active            NUMBER(1)   DEFAULT 1 NOT NULL,
    CONSTRAINT uq_supporting_units UNIQUE (entity_type, entity_id, org_unit_id),
    CONSTRAINT fk_supporting_units_org FOREIGN KEY (org_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_supporting_units_type CHECK (entity_type IN ('PROJECT', 'ACTIVITY')),
    CONSTRAINT ck_supporting_units_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE supporting_units IS 'الجهات المساندة/المشاركة في تنفيذ مشروع أو نشاط (m:n متعدد الأنواع)';
COMMENT ON COLUMN supporting_units.entity_type IS 'PROJECT أو ACTIVITY - يحدد الجدول الذي يشير إليه entity_id';

CREATE INDEX ix_supporting_units_entity ON supporting_units (entity_type, entity_id);
CREATE INDEX ix_supporting_units_org ON supporting_units (org_unit_id);

--------------------------------------------------------------------------------
-- 3. الخطط التشغيلية - اشتقاق موروث (REQ-020..022) (القسم 3.3)
--------------------------------------------------------------------------------

-- OPERATIONAL_PLANS: الخطة التشغيلية السنوية لجهة تنظيمية، مشتقة من خطة استراتيجية
-- أو من خطة تشغيلية لجهة أعلى مباشرة (وليس من الجذر دائماً - القسم 4)
CREATE TABLE operational_plans (
    op_plan_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategic_plan_id        NUMBER       NOT NULL,
    strategic_plan_version   NUMBER(6)    NOT NULL,
    org_unit_id               NUMBER      NOT NULL,
    academic_year             VARCHAR2(9) NOT NULL,
    parent_op_plan_id         NUMBER,
    status                    VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    created_by                NUMBER,
    created_at                 TIMESTAMP   DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by                 NUMBER,
    updated_at                 TIMESTAMP,
    is_active                  NUMBER(1)   DEFAULT 1 NOT NULL,
    deleted_at                  TIMESTAMP,
    CONSTRAINT uq_op_plans_unit_year UNIQUE (strategic_plan_id, org_unit_id, academic_year),
    CONSTRAINT fk_op_plans_strat_plan FOREIGN KEY (strategic_plan_id) REFERENCES strategic_plans (plan_id),
    CONSTRAINT fk_op_plans_org_unit FOREIGN KEY (org_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT fk_op_plans_parent FOREIGN KEY (parent_op_plan_id) REFERENCES operational_plans (op_plan_id),
    CONSTRAINT ck_op_plans_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED')),
    CONSTRAINT ck_op_plans_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE operational_plans IS 'الخطة التشغيلية السنوية لجهة تنظيمية، مشتقة هرمياً من جهة أعلى مباشرة';
COMMENT ON COLUMN operational_plans.strategic_plan_version IS 'يُثبّت إصدار الخطة الاستراتيجية الموروث وقت الاشتقاق (AD-01) - لا يتغير لاحقاً';
COMMENT ON COLUMN operational_plans.parent_op_plan_id IS 'الخطة الأعلى المشرفة مباشرة التي اشتُقت منها هذه الخطة (self FK)، NULL لخطة رئاسة الجامعة';

CREATE INDEX ix_op_plans_org_unit ON operational_plans (org_unit_id);
CREATE INDEX ix_op_plans_academic_year ON operational_plans (academic_year);
CREATE INDEX ix_op_plans_parent ON operational_plans (parent_op_plan_id);
CREATE INDEX ix_op_plans_strat_plan ON operational_plans (strategic_plan_id);

-- OP_PLAN_ITEMS: العناصر الموروثة (مرجعية للقراءة) + الحقول التشغيلية القابلة للتعديل
CREATE TABLE op_plan_items (
    item_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op_plan_id            NUMBER    NOT NULL,
    source_kpi_id          NUMBER   NOT NULL,
    yearly_target           NUMBER(18,4),
    responsible_unit_id     NUMBER  NOT NULL,
    is_locally_added        NUMBER(1) DEFAULT 0 NOT NULL,
    created_by              NUMBER,
    created_at                TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by                NUMBER,
    updated_at                TIMESTAMP,
    is_active                 NUMBER(1) DEFAULT 1 NOT NULL,
    deleted_at                 TIMESTAMP,
    CONSTRAINT fk_op_plan_items_plan FOREIGN KEY (op_plan_id) REFERENCES operational_plans (op_plan_id),
    CONSTRAINT fk_op_plan_items_kpi FOREIGN KEY (source_kpi_id) REFERENCES kpis (kpi_id),
    CONSTRAINT fk_op_plan_items_unit FOREIGN KEY (responsible_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_op_plan_items_local CHECK (is_locally_added IN (0, 1)),
    CONSTRAINT ck_op_plan_items_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE op_plan_items IS 'قاعدة الوراثة (RULE): تُنسخ مرجعيات العناصر من الأصل لا البيانات نفسها؛ الجهة تعدّل فقط المستهدف السنوي والجهة المسؤولة/المشاركة، وتضيف عناصر محلية';
COMMENT ON COLUMN op_plan_items.source_kpi_id IS 'العنصر الموروث (للقراءة فقط على مستوى الجهة) - أي تعديل عليه من منطق العمل يُرفض';
COMMENT ON COLUMN op_plan_items.is_locally_added IS '1 إذا أضافته الجهة (نشاط/مشروع خاص بها)';

CREATE INDEX ix_op_plan_items_plan ON op_plan_items (op_plan_id);
CREATE INDEX ix_op_plan_items_kpi ON op_plan_items (source_kpi_id);
CREATE INDEX ix_op_plan_items_unit ON op_plan_items (responsible_unit_id);

--------------------------------------------------------------------------------
-- 4. الإنجاز والتقارير (القسم 3.4)
--------------------------------------------------------------------------------

-- ACHIEVEMENTS: إدخال الإنجاز الفعلي لعنصر خطة تشغيلية عن فترة محددة
CREATE TABLE achievements (
    achievement_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    op_plan_item_id            NUMBER       NOT NULL,
    period_type                 VARCHAR2(10) NOT NULL,
    actual_value                 NUMBER(18,4),
    reported_by                  NUMBER      NOT NULL,
    approved_by                  NUMBER,
    report_snapshot_version       NUMBER(6),
    created_by                    NUMBER,
    created_at                     TIMESTAMP  DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by                     NUMBER,
    updated_at                     TIMESTAMP,
    is_active                      NUMBER(1)  DEFAULT 1 NOT NULL,
    deleted_at                      TIMESTAMP,
    CONSTRAINT fk_achievements_item FOREIGN KEY (op_plan_item_id) REFERENCES op_plan_items (item_id),
    CONSTRAINT fk_achievements_reporter FOREIGN KEY (reported_by) REFERENCES users (user_id),
    CONSTRAINT fk_achievements_approver FOREIGN KEY (approved_by) REFERENCES users (user_id),
    CONSTRAINT ck_achievements_period CHECK (period_type IN
        ('Q1', 'Q2', 'Q3', 'Q4', 'SEMESTER', 'ANNUAL')),
    CONSTRAINT ck_achievements_active CHECK (is_active IN (0, 1))
);
COMMENT ON TABLE achievements IS 'الإنجاز الفعلي المُدخل لعنصر خطة تشغيلية عن فترة زمنية محددة';
COMMENT ON COLUMN achievements.approved_by IS 'nullable حتى الاعتماد - حق الاعتماد';
COMMENT ON COLUMN achievements.report_snapshot_version IS 'يربط الإنجاز بإصدار الخطة الاستراتيجية وقت الإدخال (AD-01)';

CREATE INDEX ix_achievements_item ON achievements (op_plan_item_id);
CREATE INDEX ix_achievements_reporter ON achievements (reported_by);

--------------------------------------------------------------------------------
-- 5. سجل التدقيق (القسم 6.3، REQ-054)
--------------------------------------------------------------------------------

-- AUDIT_LOG: سجل تدقيق لكل العمليات الحساسة في النظام
CREATE TABLE audit_log (
    log_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER,
    org_unit_id       NUMBER,
    action_type        VARCHAR2(20) NOT NULL,
    entity_name          VARCHAR2(100) NOT NULL,
    entity_id             NUMBER,
    old_value              CLOB,
    new_value               CLOB,
    action_time               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ip_address                 VARCHAR2(45),
    CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_audit_log_org_unit FOREIGN KEY (org_unit_id) REFERENCES org_units (org_unit_id),
    CONSTRAINT ck_audit_log_action CHECK (action_type IN
        ('CREATE', 'UPDATE', 'APPROVE', 'DELETE', 'LOGIN', 'LOGOUT')),
    CONSTRAINT ck_audit_log_old_json CHECK (old_value IS JSON),
    CONSTRAINT ck_audit_log_new_json CHECK (new_value IS JSON)
);
COMMENT ON TABLE audit_log IS 'سجل تدقيق لكل عملية مسجَّلة (REQ-054) - يُملأ عبر triggers أو من داخل حزم الأعمال';
COMMENT ON COLUMN audit_log.old_value IS 'JSON بصيغة CLOB - القيمة قبل التعديل';
COMMENT ON COLUMN audit_log.new_value IS 'JSON بصيغة CLOB - القيمة بعد التعديل';
COMMENT ON COLUMN audit_log.ip_address IS 'يدعم IPv4/IPv6 كنص';

CREATE INDEX ix_audit_log_user ON audit_log (user_id);
CREATE INDEX ix_audit_log_entity ON audit_log (entity_name, entity_id);
CREATE INDEX ix_audit_log_time ON audit_log (action_time);

--------------------------------------------------------------------------------
-- 6. متطلبات التعريب (REQ-060، القسم 8)
--------------------------------------------------------------------------------

-- UI_LABELS: التسميات المعروضة بالعربية (والإنجليزية اختيارياً) عبر مفتاح موحّد
CREATE TABLE ui_labels (
    label_key       VARCHAR2(200) PRIMARY KEY,
    ar              VARCHAR2(1000) NOT NULL,
    en              VARCHAR2(1000)
);
COMMENT ON TABLE ui_labels IS 'REQ-060: التسميات المعروضة بالعربية عبر جدول ترجمة موحّد - أسماء الكائنات (جداول/أعمدة) بالإنجليزية دوماً';

--------------------------------------------------------------------------------
-- 7. بيانات مرجعية أولية (Seed) - أدوار وصلاحيات أساسية فقط (لا منطق أعمال)
--------------------------------------------------------------------------------

INSERT INTO roles (role_code, name_ar, name_en) VALUES ('SYS_ADMIN',    'مدير النظام',        'System Administrator');
INSERT INTO roles (role_code, name_ar, name_en) VALUES ('UNIT_MANAGER', 'مدير الجهة',          'Unit Manager');
INSERT INTO roles (role_code, name_ar, name_en) VALUES ('DATA_ENTRY',   'مدخل بيانات',         'Data Entry');
INSERT INTO roles (role_code, name_ar, name_en) VALUES ('REVIEWER',     'مراجع',               'Reviewer');
INSERT INTO roles (role_code, name_ar, name_en) VALUES ('VIEWER',       'مشاهد',               'Viewer');

INSERT INTO permissions (permission_code, name_ar, name_en) VALUES ('VIEW_REPORT',  'عرض التقارير',   'View Report');
INSERT INTO permissions (permission_code, name_ar, name_en) VALUES ('DATA_EDIT',    'تعديل البيانات', 'Edit Data');
INSERT INTO permissions (permission_code, name_ar, name_en) VALUES ('PLAN_APPROVE', 'اعتماد الخطة',   'Approve Plan');

COMMIT;
